import { Achievement } from './types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Code Commitment',
    description: 'Logged first engineering task or synced GitHub commits.',
    category: 'engineering',
    icon: '🐙',
    points: 100,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Sync GitHub commit activity via FastAPI microservice.',
  },
  {
    id: 'ach-2',
    title: 'Deep Work Specialist',
    description: 'Completed over 100 minutes of focused Deep Work in a single day.',
    category: 'engineering',
    icon: '⏱️',
    points: 250,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Log 100+ Deep Work minutes in Deep Work Service.',
  },
  {
    id: 'ach-3',
    title: 'FastAPI Architect',
    description: 'Decoupled domain layer with 0 framework imports and connected microservices.',
    category: 'engineering',
    icon: '⚡',
    points: 500,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Build pure TypeScript domain services with FastAPI backend.',
  },
  {
    id: 'ach-4',
    title: 'Unstoppable Habit Streak',
    description: 'Maintained a 7-day active execution habit streak.',
    category: 'habits',
    icon: '🔥',
    points: 300,
    unlocked: true,
    unlockedAt: '2026-07-23',
    requirementDetails: 'Maintain 7+ days streak on any habit protocol.',
  },
  {
    id: 'ach-5',
    title: 'Market Ready Candidate',
    description: 'Achieved an overall Market Readiness Score of 75%+ in the Career Engine.',
    category: 'career',
    icon: '⭐',
    points: 400,
    unlocked: true,
    unlockedAt: '2026-07-24',
    requirementDetails: 'Reach 75%+ in Career Engine pipeline calculator.',
  },
  {
    id: 'ach-6',
    title: 'Avid Reader & Scholar',
    description: 'Completed 4 growth & architecture books in the Learning Engine.',
    category: 'learning',
    icon: '📚',
    points: 200,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Finish 4 books in Learning Engine.',
  },
  {
    id: 'ach-7',
    title: 'Liquid Capital Builder',
    description: 'Accumulated over ₦2,000,000 in liquid net worth asset accounts.',
    category: 'financial',
    icon: '💰',
    points: 350,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Reach ₦2,000,000 Net Worth in Financial OS.',
  },
  {
    id: 'ach-8',
    title: 'Commercial Founder',
    description: 'Registered active commercial business entity with monthly revenue stream.',
    category: 'business',
    icon: '🏢',
    points: 450,
    unlocked: true,
    unlockedAt: '2026-07-22',
    requirementDetails: 'Log revenue for registered business entity.',
  },
  {
    id: 'ach-9',
    title: 'Master Decision Maker',
    description: 'Recorded and reviewed 5 strategic engineering decisions with lessons learned.',
    category: 'engineering',
    icon: '⚖️',
    points: 300,
    unlocked: false,
    requirementDetails: 'Log and review 5 decisions in Decision Journal.',
  },
  {
    id: 'ach-10',
    title: 'Goethe B1 German Scholar',
    description: 'Completed 2000 Anki vocabulary items for German fluency.',
    category: 'learning',
    icon: '🇩🇪',
    points: 500,
    unlocked: false,
    requirementDetails: 'Complete Goethe B1 German Flashcard deck.',
  },
];
