from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

router = APIRouter()

class WeeklyDigestRequest(BaseModel):
    engineer_name: str = "Backend & MLOps Engineer"
    week_number: int = 30
    year: int = 2026
    completed_mits_count: int = 18
    deep_work_hours: float = 14.5
    commits_pushed: int = 42
    overall_life_os_score: int = 88
    key_wins: List[str] = [
        "Shipped Project HIM OS v3.0 Notion Workspace",
        "Deployed FastAPI Microservices Backend on Vercel",
        "Achieved 96.8% accuracy on Chemical Detection ML model"
    ]

class WeeklyDigestResponse(BaseModel):
    markdown_report: str
    summary_sentence: str
    generated_at: str

@router.post("/generate", response_model=WeeklyDigestResponse)
async def generate_weekly_digest(req: WeeklyDigestRequest):
    """
    Generates an automated Weekly Execution Review Digest in Markdown format.
    """
    wins_formatted = "\n".join([f"- **Win**: {win}" for win in req.key_wins])
    
    report_md = f"""# 📊 Project HIM OS — Weekly Execution Digest (Week {req.week_number}, {req.year})
**Engineer:** {req.engineer_name}  
**Generated At:** {datetime.now().strftime("%Y-%m-%d %H:%M")}  
**Overall Life OS Rating:** {req.overall_life_os_score}% (Optimal Execution)

---

## 🎯 Weekly Performance Key Metrics
- **MITs Completed:** {req.completed_mits_count} / 21
- **Deep Work Focus:** {req.deep_work_hours} Hours
- **GitHub Commits Pushed:** {req.commits_pushed} Commits
- **System Rating:** {req.overall_life_os_score}%

---

## 🏆 Major Accomplishments & Key Wins
{wins_formatted}

---

## ⚡ Engineering & Architecture Assessment
System execution consistency remained strong throughout Week {req.week_number}. FastAPI microservices, Next.js App Router workspace, and MLOps telemetry endpoints operated with zero runtime downtime.

---
*Automated Digest generated by HIM OS Backend Microservices Engine.*
"""

    return WeeklyDigestResponse(
        markdown_report=report_md,
        summary_sentence=f"Week {req.week_number} completed with {req.completed_mits_count} MITs and {req.deep_work_hours} hrs Deep Work ({req.overall_life_os_score}% score).",
        generated_at=datetime.now().isoformat()
    )
